In [1]:
import frontmatter

md = """---
title: My Document
author: Manav
tags:
  - python
  - markdown
---

# Hello

This is the body.
"""

post = frontmatter.loads(md)

print(post.metadata)
print(post.content)

{'title': 'My Document', 'author': 'Manav', 'tags': ['python', 'markdown']}
# Hello

This is the body.


In [2]:
post.metadata

{'title': 'My Document', 'author': 'Manav', 'tags': ['python', 'markdown']}

In [4]:
post.metadata["title"] = "testing"

In [5]:
post.metadata

{'title': 'testing', 'author': 'Manav', 'tags': ['python', 'markdown']}

In [6]:
def add_line_numbers(text: str, width: int = 5) -> str:
    """
    Add stable line numbers to Markdown text.

    Example:
        # Title
        Hello

    becomes:
        00001 | # Title
        00002 | Hello
    """
    lines = text.splitlines()

    return "\n".join(
        f"{i:0{width}d} | {line}"
        for i, line in enumerate(lines, start=1)
    )

In [7]:
md = """# Introduction

This is some text.

## Installation

Install the package.
"""

numbered = add_line_numbers(md)

print(numbered)

00001 | # Introduction
00002 | 
00003 | This is some text.
00004 | 
00005 | ## Installation
00006 | 
00007 | Install the package.


In [8]:
import difflib

old = """# Introduction

This is the old content.

## Installation

Install the package.
"""

new = """# Introduction

This is the updated content.

## Installation

Install the package using pip.

## Usage

Use the package like this.
"""

diff = difflib.unified_diff(
    old.splitlines(),
    new.splitlines(),
    fromfile="old.md",
    tofile="new.md",
    lineterm=""
)

print("\n".join(diff))

--- old.md
+++ new.md
@@ -1,7 +1,11 @@
 # Introduction
 
-This is the old content.
+This is the updated content.
 
 ## Installation
 
-Install the package.
+Install the package using pip.
+
+## Usage
+
+Use the package like this.


In [1]:
import tiktoken

In [2]:
CHUNK_SIZE = 4096
ENCODER = tiktoken.encoding_for_model("gpt-4o-mini")

In [3]:
content = """
OpenAI's large language models process text using tokens, which are common sequences of characters found in a set of text. The models learn to understand the statistical relationships between these tokens, and excel at producing the next token in a sequence of tokens.
"""

In [4]:
tokens = ENCODER.encode(content)

In [5]:
tokens

[198,
 6447,
 17527,
 885,
 4410,
 6439,
 7015,
 2273,
 2201,
 2360,
 20290,
 11,
 1118,
 553,
 5355,
 45665,
 328,
 9862,
 2491,
 306,
 261,
 920,
 328,
 2201,
 13,
 623,
 7015,
 4484,
 316,
 4218,
 290,
 39535,
 14321,
 2870,
 1879,
 20290,
 11,
 326,
 19383,
 540,
 24168,
 290,
 2613,
 6602,
 306,
 261,
 16281,
 328,
 20290,
 558]

In [6]:
 encode = [198, 6447, 17527]

In [8]:
content = ENCODER.decode(encode)

In [9]:
content

'\nOpenAI'

In [10]:
ENCODER.encode("hi")

[3686]

In [1]:
from composer import Vector

In [2]:
BASE_URL="http://10.10.112.110:8000/v1"
API_KEY="gw-bd2c534fd39e474ecbfbb333f8fddad00559eb22a664b55f"
LLM="DeepSeek"
VLM="VisionChat"
EMB="Qwen3-Embedding-8B"

In [3]:
vec = Vector(
    base_url=BASE_URL,
    api_key=API_KEY,
    model=EMB
)

In [27]:
resp = vec.vector(["hii", "second one"])

In [28]:
resp[0]

array([ 0.02867888,  0.01642097, -0.02601915, ..., -0.0173461 ,
       -0.00714081,  0.00821049], shape=(4096,))

In [29]:
resp[1]

array([ 0.04240227,  0.0230941 , -0.00187718, ..., -0.01892959,
        0.00225578,  0.00959099], shape=(4096,))

In [30]:
q = vec.vector("test")

In [31]:
resp

array([[ 0.02867888,  0.01642097, -0.02601915, ..., -0.0173461 ,
        -0.00714081,  0.00821049],
       [ 0.04240227,  0.0230941 , -0.00187718, ..., -0.01892959,
         0.00225578,  0.00959099]], shape=(2, 4096))

In [32]:
s = resp @ q.T

In [33]:
s

array([0.65925813, 0.71624385])

In [23]:
import numpy as np

In [25]:
top_indices = np.argpartition(s, -1)[-1:]

In [26]:
top_indices

array([1])